### ISSUE TITLE
Subtle yet serious bug in BitTools.FindBitPattern

### ISSUE THREAD

**Issue by carlospuk** [loarabia/ManagedMediaHelpers#12]
I may be mistaken but I think there is a flaw in the method 

```
FindBitPattern(byte[] data, byte[] pattern, byte[] mask, int startIndex, int endIndex)
```

Consider searching for the pattern {00,00,01} in the array  {00,00,00,01}

The while() loop begins incrementing the pati variable as it seems that there is a match.  However, when it reaches the third element of the array, it fails to find the third byte of the pattern, but does NOT seek back to look for the pattern at the next possible location.  Instead, it continues to move through the array from the next element and misses the match altogether.

This can be corrected by adding these lines:

```
while (di < endIndex)
        {
            if (pattern[pati] == (data[di] & mask[pati]))
            {
                pati++;
            }
            else if (pattern[pati] != (data[di] & mask[pati]))
            {
                // If we were in the middle of matching a pattern, move back in case the pattern occurred within this section
                if (pati > 0)
                {
                    di -= pati;
                }

                pati = 0;
            }
            else
            {
                Debug.Assert(false, "All possible states should have already been covered.");
            }
```

Hope this helps

Carlos

**Comment by loarabia** [comment]
Good catch. Thats got it. I'll add the change and push.
